// flow-typed signature: 6984782650a0d99ffcd6ffb0493a8f36
// flow-typed version: <<STUB>>/redux-immutablejs_v^0.0.8/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutablejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutablejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-immutablejs/lib/index' {
  declare module.exports: any;
}

declare module 'redux-immutablejs/lib/utils/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-immutablejs/lib/utils/createReducer' {
  declare module.exports: any;
}

declare module 'redux-immutablejs/src/index' {
  declare module.exports: any;
}

declare module 'redux-immutablejs/src/utils/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-immutablejs/src/utils/createReducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-immutablejs/lib/index.js' {
  declare module.exports: $Exports<'redux-immutablejs/lib/index'>;
}
declare module 'redux-immutablejs/lib/utils/combineReducers.js' {
  declare module.exports: $Exports<'redux-immutablejs/lib/utils/combineReducers'>;
}
declare module 'redux-immutablejs/lib/utils/createReducer.js' {
  declare module.exports: $Exports<'redux-immutablejs/lib/utils/createReducer'>;
}
declare module 'redux-immutablejs/src/index.js' {
  declare module.exports: $Exports<'redux-immutablejs/src/index'>;
}
declare module 'redux-immutablejs/src/utils/combineReducers.js' {
  declare module.exports: $Exports<'redux-immutablejs/src/utils/combineReducers'>;
}
declare module 'redux-immutablejs/src/utils/createReducer.js' {
  declare module.exports: $Exports<'redux-immutablejs/src/utils/createReducer'>;
}
